"""Added WorkoutLog model

Revision ID: 147aab0e82e3
Revises: fdc8ea10093c
Create Date: 2025-06-18 09:35:03.671706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147aab0e82e3'
down_revision = 'fdc8ea10093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('date_completed', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_logs')
    # ### end Alembic commands ###
