"""Added progression fields

Revision ID: 9f2cb9ec0b1f
Revises: 147aab0e82e3
Create Date: 2025-06-18 10:18:36.787122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2cb9ec0b1f'
down_revision = '147aab0e82e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progression_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progression_weight_increment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('progression_reps_increment', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('progression_reps_increment')
        batch_op.drop_column('progression_weight_increment')
        batch_op.drop_column('progression_interval')

    # ### end Alembic commands ###
