"""Added various fields

Revision ID: fdc8ea10093c
Revises: 66c3d0014cfb
Create Date: 2025-06-15 21:17:45.755319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc8ea10093c'
down_revision = '66c3d0014cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('equipment', sa.String(length=64), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('description')
        batch_op.drop_column('duration')
        batch_op.drop_column('type')

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('rest_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('equipment')
        batch_op.drop_column('category')
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
